//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ToDoPlanner.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ToDoWSSoap", Namespace="http://tempuri.org/")]
    public partial class ToDoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearTelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTelefonosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTareasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarTelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarTelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarTareaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ToDoWS() {
            this.Url = "http://www.todoplanner.somee.com/ToDoWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearTelefonoCompletedEventHandler CrearTelefonoCompleted;
        
        /// <remarks/>
        public event CrearCorreoCompletedEventHandler CrearCorreoCompleted;
        
        /// <remarks/>
        public event CrearTareaCompletedEventHandler CrearTareaCompleted;
        
        /// <remarks/>
        public event ObtenerTelefonosCompletedEventHandler ObtenerTelefonosCompleted;
        
        /// <remarks/>
        public event ObtenerCorreosCompletedEventHandler ObtenerCorreosCompleted;
        
        /// <remarks/>
        public event ObtenerTareasCompletedEventHandler ObtenerTareasCompleted;
        
        /// <remarks/>
        public event ActualizarTelefonoCompletedEventHandler ActualizarTelefonoCompleted;
        
        /// <remarks/>
        public event ActualizarCorreoCompletedEventHandler ActualizarCorreoCompleted;
        
        /// <remarks/>
        public event ActualizarTareaCompletedEventHandler ActualizarTareaCompleted;
        
        /// <remarks/>
        public event BorrarTelefonoCompletedEventHandler BorrarTelefonoCompleted;
        
        /// <remarks/>
        public event BorrarCorreoCompletedEventHandler BorrarCorreoCompleted;
        
        /// <remarks/>
        public event BorrarTareaCompletedEventHandler BorrarTareaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearTelefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearTelefono(int telefono, string descripcion) {
            object[] results = this.Invoke("CrearTelefono", new object[] {
                        telefono,
                        descripcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearTelefonoAsync(int telefono, string descripcion) {
            this.CrearTelefonoAsync(telefono, descripcion, null);
        }
        
        /// <remarks/>
        public void CrearTelefonoAsync(int telefono, string descripcion, object userState) {
            if ((this.CrearTelefonoOperationCompleted == null)) {
                this.CrearTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearTelefonoOperationCompleted);
            }
            this.InvokeAsync("CrearTelefono", new object[] {
                        telefono,
                        descripcion}, this.CrearTelefonoOperationCompleted, userState);
        }
        
        private void OnCrearTelefonoOperationCompleted(object arg) {
            if ((this.CrearTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearTelefonoCompleted(this, new CrearTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearCorreo(string correo, string descripcion) {
            object[] results = this.Invoke("CrearCorreo", new object[] {
                        correo,
                        descripcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCorreoAsync(string correo, string descripcion) {
            this.CrearCorreoAsync(correo, descripcion, null);
        }
        
        /// <remarks/>
        public void CrearCorreoAsync(string correo, string descripcion, object userState) {
            if ((this.CrearCorreoOperationCompleted == null)) {
                this.CrearCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCorreoOperationCompleted);
            }
            this.InvokeAsync("CrearCorreo", new object[] {
                        correo,
                        descripcion}, this.CrearCorreoOperationCompleted, userState);
        }
        
        private void OnCrearCorreoOperationCompleted(object arg) {
            if ((this.CrearCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCorreoCompleted(this, new CrearCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearTarea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearTarea(string descripcion) {
            object[] results = this.Invoke("CrearTarea", new object[] {
                        descripcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearTareaAsync(string descripcion) {
            this.CrearTareaAsync(descripcion, null);
        }
        
        /// <remarks/>
        public void CrearTareaAsync(string descripcion, object userState) {
            if ((this.CrearTareaOperationCompleted == null)) {
                this.CrearTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearTareaOperationCompleted);
            }
            this.InvokeAsync("CrearTarea", new object[] {
                        descripcion}, this.CrearTareaOperationCompleted, userState);
        }
        
        private void OnCrearTareaOperationCompleted(object arg) {
            if ((this.CrearTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearTareaCompleted(this, new CrearTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerTelefonos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerTelefonos() {
            object[] results = this.Invoke("ObtenerTelefonos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTelefonosAsync() {
            this.ObtenerTelefonosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerTelefonosAsync(object userState) {
            if ((this.ObtenerTelefonosOperationCompleted == null)) {
                this.ObtenerTelefonosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTelefonosOperationCompleted);
            }
            this.InvokeAsync("ObtenerTelefonos", new object[0], this.ObtenerTelefonosOperationCompleted, userState);
        }
        
        private void OnObtenerTelefonosOperationCompleted(object arg) {
            if ((this.ObtenerTelefonosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTelefonosCompleted(this, new ObtenerTelefonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerCorreos() {
            object[] results = this.Invoke("ObtenerCorreos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCorreosAsync() {
            this.ObtenerCorreosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerCorreosAsync(object userState) {
            if ((this.ObtenerCorreosOperationCompleted == null)) {
                this.ObtenerCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCorreosOperationCompleted);
            }
            this.InvokeAsync("ObtenerCorreos", new object[0], this.ObtenerCorreosOperationCompleted, userState);
        }
        
        private void OnObtenerCorreosOperationCompleted(object arg) {
            if ((this.ObtenerCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCorreosCompleted(this, new ObtenerCorreosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerTareas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerTareas() {
            object[] results = this.Invoke("ObtenerTareas", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTareasAsync() {
            this.ObtenerTareasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerTareasAsync(object userState) {
            if ((this.ObtenerTareasOperationCompleted == null)) {
                this.ObtenerTareasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTareasOperationCompleted);
            }
            this.InvokeAsync("ObtenerTareas", new object[0], this.ObtenerTareasOperationCompleted, userState);
        }
        
        private void OnObtenerTareasOperationCompleted(object arg) {
            if ((this.ObtenerTareasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTareasCompleted(this, new ObtenerTareasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarTelefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizarTelefono(int id_telefono, int telefono, string descripcion) {
            object[] results = this.Invoke("ActualizarTelefono", new object[] {
                        id_telefono,
                        telefono,
                        descripcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarTelefonoAsync(int id_telefono, int telefono, string descripcion) {
            this.ActualizarTelefonoAsync(id_telefono, telefono, descripcion, null);
        }
        
        /// <remarks/>
        public void ActualizarTelefonoAsync(int id_telefono, int telefono, string descripcion, object userState) {
            if ((this.ActualizarTelefonoOperationCompleted == null)) {
                this.ActualizarTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarTelefonoOperationCompleted);
            }
            this.InvokeAsync("ActualizarTelefono", new object[] {
                        id_telefono,
                        telefono,
                        descripcion}, this.ActualizarTelefonoOperationCompleted, userState);
        }
        
        private void OnActualizarTelefonoOperationCompleted(object arg) {
            if ((this.ActualizarTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarTelefonoCompleted(this, new ActualizarTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizarCorreo(int id_correo, string correo, string descripcion) {
            object[] results = this.Invoke("ActualizarCorreo", new object[] {
                        id_correo,
                        correo,
                        descripcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarCorreoAsync(int id_correo, string correo, string descripcion) {
            this.ActualizarCorreoAsync(id_correo, correo, descripcion, null);
        }
        
        /// <remarks/>
        public void ActualizarCorreoAsync(int id_correo, string correo, string descripcion, object userState) {
            if ((this.ActualizarCorreoOperationCompleted == null)) {
                this.ActualizarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarCorreoOperationCompleted);
            }
            this.InvokeAsync("ActualizarCorreo", new object[] {
                        id_correo,
                        correo,
                        descripcion}, this.ActualizarCorreoOperationCompleted, userState);
        }
        
        private void OnActualizarCorreoOperationCompleted(object arg) {
            if ((this.ActualizarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCorreoCompleted(this, new ActualizarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarTarea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizarTarea(int id_tarea, string tarea) {
            object[] results = this.Invoke("ActualizarTarea", new object[] {
                        id_tarea,
                        tarea});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarTareaAsync(int id_tarea, string tarea) {
            this.ActualizarTareaAsync(id_tarea, tarea, null);
        }
        
        /// <remarks/>
        public void ActualizarTareaAsync(int id_tarea, string tarea, object userState) {
            if ((this.ActualizarTareaOperationCompleted == null)) {
                this.ActualizarTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarTareaOperationCompleted);
            }
            this.InvokeAsync("ActualizarTarea", new object[] {
                        id_tarea,
                        tarea}, this.ActualizarTareaOperationCompleted, userState);
        }
        
        private void OnActualizarTareaOperationCompleted(object arg) {
            if ((this.ActualizarTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarTareaCompleted(this, new ActualizarTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarTelefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BorrarTelefono(int id_telefono) {
            object[] results = this.Invoke("BorrarTelefono", new object[] {
                        id_telefono});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarTelefonoAsync(int id_telefono) {
            this.BorrarTelefonoAsync(id_telefono, null);
        }
        
        /// <remarks/>
        public void BorrarTelefonoAsync(int id_telefono, object userState) {
            if ((this.BorrarTelefonoOperationCompleted == null)) {
                this.BorrarTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarTelefonoOperationCompleted);
            }
            this.InvokeAsync("BorrarTelefono", new object[] {
                        id_telefono}, this.BorrarTelefonoOperationCompleted, userState);
        }
        
        private void OnBorrarTelefonoOperationCompleted(object arg) {
            if ((this.BorrarTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarTelefonoCompleted(this, new BorrarTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BorrarCorreo(int id_correo) {
            object[] results = this.Invoke("BorrarCorreo", new object[] {
                        id_correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarCorreoAsync(int id_correo) {
            this.BorrarCorreoAsync(id_correo, null);
        }
        
        /// <remarks/>
        public void BorrarCorreoAsync(int id_correo, object userState) {
            if ((this.BorrarCorreoOperationCompleted == null)) {
                this.BorrarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarCorreoOperationCompleted);
            }
            this.InvokeAsync("BorrarCorreo", new object[] {
                        id_correo}, this.BorrarCorreoOperationCompleted, userState);
        }
        
        private void OnBorrarCorreoOperationCompleted(object arg) {
            if ((this.BorrarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarCorreoCompleted(this, new BorrarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarTarea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BorrarTarea(int id_tarea) {
            object[] results = this.Invoke("BorrarTarea", new object[] {
                        id_tarea});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarTareaAsync(int id_tarea) {
            this.BorrarTareaAsync(id_tarea, null);
        }
        
        /// <remarks/>
        public void BorrarTareaAsync(int id_tarea, object userState) {
            if ((this.BorrarTareaOperationCompleted == null)) {
                this.BorrarTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarTareaOperationCompleted);
            }
            this.InvokeAsync("BorrarTarea", new object[] {
                        id_tarea}, this.BorrarTareaOperationCompleted, userState);
        }
        
        private void OnBorrarTareaOperationCompleted(object arg) {
            if ((this.BorrarTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarTareaCompleted(this, new BorrarTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearTelefonoCompletedEventHandler(object sender, CrearTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearCorreoCompletedEventHandler(object sender, CrearCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearTareaCompletedEventHandler(object sender, CrearTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerTelefonosCompletedEventHandler(object sender, ObtenerTelefonosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTelefonosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTelefonosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerCorreosCompletedEventHandler(object sender, ObtenerCorreosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCorreosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCorreosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerTareasCompletedEventHandler(object sender, ObtenerTareasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTareasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTareasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActualizarTelefonoCompletedEventHandler(object sender, ActualizarTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActualizarCorreoCompletedEventHandler(object sender, ActualizarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActualizarTareaCompletedEventHandler(object sender, ActualizarTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BorrarTelefonoCompletedEventHandler(object sender, BorrarTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BorrarCorreoCompletedEventHandler(object sender, BorrarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BorrarTareaCompletedEventHandler(object sender, BorrarTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591