#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LifePlanner.Resource", IsApplication=true)]

namespace LifePlanner
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int botonesHorizontales = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int btn_actualizar = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int btn_actualizarTarea = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int btn_agregar = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int btn_agregarTarea = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int btn_borrar = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int btn_borrarTarea = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int btn_contactos = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int btn_correosVolver = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int btn_tareas = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int btn_tareasVolver = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int listaTareas = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int listaUsuarios = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int tareas = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int txt_correo = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txt_nombre = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int txt_tarea = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int txt_telefono = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int usuarios = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactosLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TareasLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
