//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ContactApp.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ToDoWSSoap", Namespace="http://tempuri.org/")]
    public partial class ToDoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearUsarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ToDoWS() {
            this.Url = "http://todoplanner.somee.com/ToDoWs.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearUsarioCompletedEventHandler CrearUsarioCompleted;
        
        /// <remarks/>
        public event ObtenerUsuarioCompletedEventHandler ObtenerUsuarioCompleted;
        
        /// <remarks/>
        public event ActualizarUsuarioCompletedEventHandler ActualizarUsuarioCompleted;
        
        /// <remarks/>
        public event BorrarUsuarioCompletedEventHandler BorrarUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearUsario(string nombre, string correo, int telefono) {
            object[] results = this.Invoke("CrearUsario", new object[] {
                        nombre,
                        correo,
                        telefono});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsarioAsync(string nombre, string correo, int telefono) {
            this.CrearUsarioAsync(nombre, correo, telefono, null);
        }
        
        /// <remarks/>
        public void CrearUsarioAsync(string nombre, string correo, int telefono, object userState) {
            if ((this.CrearUsarioOperationCompleted == null)) {
                this.CrearUsarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsario", new object[] {
                        nombre,
                        correo,
                        telefono}, this.CrearUsarioOperationCompleted, userState);
        }
        
        private void OnCrearUsarioOperationCompleted(object arg) {
            if ((this.CrearUsarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsarioCompleted(this, new CrearUsarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerUsuario() {
            object[] results = this.Invoke("ObtenerUsuario", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerUsuarioAsync() {
            this.ObtenerUsuarioAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerUsuarioAsync(object userState) {
            if ((this.ObtenerUsuarioOperationCompleted == null)) {
                this.ObtenerUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerUsuario", new object[0], this.ObtenerUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerUsuarioCompleted(this, new ObtenerUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizarUsuario(int id, string nombre, string correo, int telefono) {
            object[] results = this.Invoke("ActualizarUsuario", new object[] {
                        id,
                        nombre,
                        correo,
                        telefono});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarUsuarioAsync(int id, string nombre, string correo, int telefono) {
            this.ActualizarUsuarioAsync(id, nombre, correo, telefono, null);
        }
        
        /// <remarks/>
        public void ActualizarUsuarioAsync(int id, string nombre, string correo, int telefono, object userState) {
            if ((this.ActualizarUsuarioOperationCompleted == null)) {
                this.ActualizarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ActualizarUsuario", new object[] {
                        id,
                        nombre,
                        correo,
                        telefono}, this.ActualizarUsuarioOperationCompleted, userState);
        }
        
        private void OnActualizarUsuarioOperationCompleted(object arg) {
            if ((this.ActualizarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarUsuarioCompleted(this, new ActualizarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BorrarUsuario(int id) {
            object[] results = this.Invoke("BorrarUsuario", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarUsuarioAsync(int id) {
            this.BorrarUsuarioAsync(id, null);
        }
        
        /// <remarks/>
        public void BorrarUsuarioAsync(int id, object userState) {
            if ((this.BorrarUsuarioOperationCompleted == null)) {
                this.BorrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("BorrarUsuario", new object[] {
                        id}, this.BorrarUsuarioOperationCompleted, userState);
        }
        
        private void OnBorrarUsuarioOperationCompleted(object arg) {
            if ((this.BorrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarUsuarioCompleted(this, new BorrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearUsarioCompletedEventHandler(object sender, CrearUsarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerUsuarioCompletedEventHandler(object sender, ObtenerUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActualizarUsuarioCompletedEventHandler(object sender, ActualizarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BorrarUsuarioCompletedEventHandler(object sender, BorrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591